hostname: PE1234
mgmt_ip: "10.10.12.34"
uplinks:
  - name: Gig1/0/2
    ip: "10.0.0.1"
vrfs:
  - name: Red
    rd: "1:1"
  - name: Yellow
    rd: "2:2"
ces:
  - name: Gig1/0/3
    ip: "10.0.100.1"
    vrf: Red
  - name: Loopback666
    ip: "10.0.200.1"
    vrf: Yellow